trigger:
  branches:
    include:
    - '*'

resources:
  pipelines:
  - pipeline: 'Package-Pipeline'
    source: '<@package-pipeline-name@>'
    trigger:
      branches:
      include:
          - releases/*
          - develop
          exclude:
          - feature/*
          - master

pool:
  vmImage: ubuntu-latest

variables:
  # kubernetes deployment files path. 
  manifests: '$(System.DefaultWorkingDirectory)/$(deployFiles)'

steps:   
  - task: KubectlInstaller@0
    displayName: 'Install Kubectl latest'

  - task: Kubernetes@1
      displayName: 'Create Namespace'
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: '$(k8s_service_connection)'
        command: 'apply'
        useConfigurationFile: true
        configurationType: 'inline'
        inline: '{ "kind": "Namespace", "apiVersion": "v1", "metadata": { "name": "$(k8sNamespace)" }}'
        
  - task: Kubernetes@1
    displayName: 'Kubectl apply'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: '$(k8s_service_connection)'
      namespace: '$(k8sNamespace)'
      command: 'apply'
      useConfigurationFile: true
      configuration: '$(manifests)'
      
    
    
        
             
   
              
    
    
