trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  terraformWorkingDirectory: '$(System.DefaultWorkingDirectory)/.pipelines/scripts/terraform/aws/eks'

steps:

- task: TerraformInstaller@0
  displayName: 'Install Terraform latest'
  inputs:
    terraformVersion: 'latest' 

- task: TerraformTaskV2@2
  displayName: 'Terraform : init'
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: "$(terraformWorkingDirectory)"
    commandOptions: "-var cluster_name=$(cluster_name)"
    backendServiceAWS: "$(awsServiceConnection)"
    backendAWSBucketName: "$(awsS3BucketName)"
    backendAWSKey: "$(awsS3KeyPath)"

- task: TerraformTaskV2@2
  displayName: 'Terraform : plan'
  inputs:
    provider: 'aws'
    command: 'plan'
    workingDirectory: "$(terraformWorkingDirectory)"
    commandOptions: "-var cluster_name=$(cluster_name)"
    environmentServiceNameAWS: "$(awsServiceConnection)"

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
  displayName: 'Terraform : apply'
  inputs:
    provider: aws
    command: apply
    workingDirectory: "$(terraformWorkingDirectory)"
    commandOptions: "-var cluster_name=$(cluster_name)"
    environmentServiceNameAWS: "$(awsServiceConnection)"
