trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  terraformWorkingDirectory: '$(System.DefaultWorkingDirectory)/.terraform/eks'

steps:

- task: TerraformInstaller@0
  displayName: 'Install Terraform latest'
  inputs:
    terraformVersion: 'latest' 

- task: TerraformTaskV2@2
  displayName: 'Terraform : init'
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: "$(terraformWorkingDirectory)"
    backendServiceAWS: "$(awsServiceConnection)"
    backendAWSBucketName: "$(awsS3BucketName)"
    backendAWSKey: "$(awsS3KeyPath)"

- task: TerraformTaskV2@2
  displayName: 'Terraform : apply'
  name: terraformApply
  inputs:
    provider: aws
    command: apply
    workingDirectory: "$(terraformWorkingDirectory)"
    environmentServiceNameAWS: "$(awsServiceConnection)"

- publish: $(terraformWorkingDirectory)/kubeconfig
  displayName: 'Publish Kubeconfig Artifact'
  artifact: kubeconfig