name: Build docs


on:

  push:
    paths:
      - documentation/github/pipelines/test_include.asciidoc
    branches:
      - '**'


jobs:

  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Install asciidoctor-reducer
        run: sudo gem install asciidoctor-reducer --pre

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Reduce readme
        run: asciidoctor-reducer -o documentation/github/pipelines/test_include_done.asciidoc documentation/github/pipelines/test_include.asciidoc

      - name: Commit readme
        uses: EndBug/add-and-commit@v8